CREATE TABLE IF NOT EXISTS copilot_mcp_servers (
    id CHAR(36) NOT NULL,
    name VARCHAR(128) NOT NULL,
    command VARCHAR(512) NOT NULL DEFAULT '',
    args JSON NOT NULL,
    env JSON NOT NULL,
    url VARCHAR(512) NOT NULL DEFAULT '',
    enabled TINYINT(1) NOT NULL DEFAULT 1,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY copilot_mcp_servers_name_idx (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
