CREATE TABLE IF NOT EXISTS copilot_alerts (
    id CHAR(36) NOT NULL,
    external_id VARCHAR(255) NOT NULL,
    source VARCHAR(64) NOT NULL DEFAULT '',
    title VARCHAR(512) NOT NULL DEFAULT '',
    description TEXT NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'warning',
    status VARCHAR(16) NOT NULL DEFAULT 'firing',
    environment VARCHAR(64) NOT NULL DEFAULT '',
    domain VARCHAR(64) NOT NULL DEFAULT '',
    resource_type VARCHAR(64) NOT NULL DEFAULT '',
    resource_name VARCHAR(255) NOT NULL DEFAULT '',
    labels JSON NOT NULL,
    raw JSON NULL,
    fired_at DATETIME(6) NOT NULL,
    resolved_at DATETIME(6) NULL,
    received_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY copilot_alerts_identity_idx (source, external_id),
    KEY copilot_alerts_status_severity_idx (status, severity),
    KEY copilot_alerts_environment_status_idx (environment, status),
    KEY copilot_alerts_updated_at_idx (updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
